### ISSUE TITLE
Copy over manifest.json?

### ISSUE THREAD

**Issue by 0xAlwaysDumpling** [harrysolovay/react-app-rewire-blockstack#1]
I think the only thing missing is copying over the manifest.json for blockstack? When you run the dev server  and click sign in to block stack it'll ask for permissions for create-react-app!

**Comment by harrysolovay** [comment]
Sorry to hear you're running into trouble. Can you please show me your usage (both in `config-overrides` and in your Blockstack API call)?

**Comment by 0xAlwaysDumpling** [comment]
Hey Harry, I believe the manifest.json defines the blockstack app on redirect for auth. Correct me if I'm wrong, in the typical blockstack starter project you have a manifest.json file defined in src/assets. I believe on dev server you are still using the CRA manifest. Happy to connect offline if needed and by the way good work on the rewiring just what I happen to be looking for last night.

![bs](https://user-images.githubusercontent.com/8901270/45510383-0ac58a00-b768-11e8-8abd-d3a55347d3aa.png)

**Comment by harrysolovay** [comment]
In CRA-bootstrapped projects, the `manifest.json` is in `~/public`, not `~/src` (might be the source of your probem). If you're looking to define the app metadata (to be reflected in the Blockstack login screen), you'll need to work on that file (which gets requested from your server). In development, `react-app-rewire-blockstack` allows you to configure the CRA Webpack dev server to allow incoming requests from Blockstack (for the `manifest.json`). The good news is that it looks like the rewire works! Even though you haven't defined the app's metadata in `~/public/manifest.json`, the non-edited file is copied into the temporary webpack dev server build. If not for this, you'd be getting an error when redirecting to the authentication portal.

**Comment by 0xAlwaysDumpling** [comment]
You are right :+1:  I missed the manifest.json in public
